# Generated by Django 3.2.4 on 2021-06-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niskize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='profile',
            new_name='user',
        ),
    ]
