# Generated by Django 3.2.2 on 2021-06-08 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('niskize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
