# Generated by Django 3.2.4 on 2021-06-09 13:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niskize', '0002_auto_20210609_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='posts image'),
        ),
    ]
