# Generated by Django 3.2.4 on 2021-06-08 21:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niskize', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='article image'),
        ),
    ]
