# Generated by Django 3.2.4 on 2021-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niskize', '0004_auto_20210609_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
