# Generated by Django 3.2.4 on 2021-06-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niskize', '0011_alter_comment_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
